name: todo_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  build_runner: ^2.1.11

  # Firebase
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1

  # For Model
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  json_serializable: ^6.3.1

  # Riverpod
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
